module.exports = {
  apps: [
    {
      name: 'hphi-revamp',
      script: 'node_modules/next/dist/bin/next',
      args: 'start -p 4002',
      cwd: '/home/yamada/workspace/hphi/hphi-revamp',
      exec_mode: 'cluster',
      instances: 1,
      max_memory_restart: '1G',
      interpreter: '/home/yamada/.nvm/versions/node/v22.12.0/bin/node',
      time: false,
      watch: true,
      watch_delay: 10000,
      ignore_watch: ['[/\\]./', 'node_modules', 'volumes', 'logs', '.next', 'public'],
      source_map_support: false,
      instance_var: 'NODE_APP_INSTANCE',
      error_file: '/home/yamada/workspace/hphi/hphi-revamp/logs/hphi-revamp-error.log',
      out_file: '/home/yamada/workspace/hphi/hphi-revamp/logs/hphi-revamp-out.log',
      merge_logs: true,
      min_uptime: '10m',
      listen_timeout: 10000,
      kill_timeout: 10000,
      wait_ready: true,
      max_restarts: 3,
      restart_delay: 3000,
      autorestart: true,
      vizion: false,
    },
  ],
}
